// Automatically generated by forge bind-json.
pragma solidity >=0.6.2 <0.9.0;
pragma experimental ABIEncoderV2;

import {EIP712Types} from 'src/libraries/types/EIP712Types.sol';

interface Vm {
  function parseJsonTypeArray(
    string calldata json,
    string calldata key,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function parseJsonType(
    string calldata json,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function parseJsonType(
    string calldata json,
    string calldata key,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function serializeJsonType(
    string calldata typeDescription,
    bytes memory value
  ) external pure returns (string memory json);

  function serializeJsonType(
    string calldata objectKey,
    string calldata valueKey,
    string calldata typeDescription,
    bytes memory value
  ) external returns (string memory json);
}

library JsonBindings {
  Vm constant vm = Vm(address(uint160(uint256(keccak256('hevm cheat code')))));

  // prettier-ignore
  string constant schema_SetUserPositionManager = "SetUserPositionManager(address positionManager,address user,bool approve,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_Permit = "Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_Supply = "Supply(address spoke,uint256 reserveId,uint256 amount,address onBehalfOf,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_Withdraw = "Withdraw(address spoke,uint256 reserveId,uint256 amount,address onBehalfOf,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_Borrow = "Borrow(address spoke,uint256 reserveId,uint256 amount,address onBehalfOf,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_Repay = "Repay(address spoke,uint256 reserveId,uint256 amount,address onBehalfOf,uint256 nonce,uint256 deadline)";

  function serialize(
    EIP712Types.SetUserPositionManager memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_SetUserPositionManager, abi.encode(value));
  }

  function serialize(
    EIP712Types.SetUserPositionManager memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return
      vm.serializeJsonType(objectKey, valueKey, schema_SetUserPositionManager, abi.encode(value));
  }

  function deserializeSetUserPositionManager(
    string memory json
  ) public pure returns (EIP712Types.SetUserPositionManager memory) {
    return
      abi.decode(
        vm.parseJsonType(json, schema_SetUserPositionManager),
        (EIP712Types.SetUserPositionManager)
      );
  }

  function deserializeSetUserPositionManager(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetUserPositionManager memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_SetUserPositionManager),
        (EIP712Types.SetUserPositionManager)
      );
  }

  function deserializeSetUserPositionManagerArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetUserPositionManager[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_SetUserPositionManager),
        (EIP712Types.SetUserPositionManager[])
      );
  }

  function serialize(EIP712Types.Permit memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_Permit, abi.encode(value));
  }

  function serialize(
    EIP712Types.Permit memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_Permit, abi.encode(value));
  }

  function deserializePermit(string memory json) public pure returns (EIP712Types.Permit memory) {
    return abi.decode(vm.parseJsonType(json, schema_Permit), (EIP712Types.Permit));
  }

  function deserializePermit(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Permit memory) {
    return abi.decode(vm.parseJsonType(json, path, schema_Permit), (EIP712Types.Permit));
  }

  function deserializePermitArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Permit[] memory) {
    return abi.decode(vm.parseJsonTypeArray(json, path, schema_Permit), (EIP712Types.Permit[]));
  }

  function serialize(EIP712Types.Supply memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_Supply, abi.encode(value));
  }

  function serialize(
    EIP712Types.Supply memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_Supply, abi.encode(value));
  }

  function deserializeSupply(string memory json) public pure returns (EIP712Types.Supply memory) {
    return abi.decode(vm.parseJsonType(json, schema_Supply), (EIP712Types.Supply));
  }

  function deserializeSupply(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Supply memory) {
    return abi.decode(vm.parseJsonType(json, path, schema_Supply), (EIP712Types.Supply));
  }

  function deserializeSupplyArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Supply[] memory) {
    return abi.decode(vm.parseJsonTypeArray(json, path, schema_Supply), (EIP712Types.Supply[]));
  }

  function serialize(EIP712Types.Withdraw memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_Withdraw, abi.encode(value));
  }

  function serialize(
    EIP712Types.Withdraw memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_Withdraw, abi.encode(value));
  }

  function deserializeWithdraw(
    string memory json
  ) public pure returns (EIP712Types.Withdraw memory) {
    return abi.decode(vm.parseJsonType(json, schema_Withdraw), (EIP712Types.Withdraw));
  }

  function deserializeWithdraw(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Withdraw memory) {
    return abi.decode(vm.parseJsonType(json, path, schema_Withdraw), (EIP712Types.Withdraw));
  }

  function deserializeWithdrawArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Withdraw[] memory) {
    return abi.decode(vm.parseJsonTypeArray(json, path, schema_Withdraw), (EIP712Types.Withdraw[]));
  }

  function serialize(EIP712Types.Borrow memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_Borrow, abi.encode(value));
  }

  function serialize(
    EIP712Types.Borrow memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_Borrow, abi.encode(value));
  }

  function deserializeBorrow(string memory json) public pure returns (EIP712Types.Borrow memory) {
    return abi.decode(vm.parseJsonType(json, schema_Borrow), (EIP712Types.Borrow));
  }

  function deserializeBorrow(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Borrow memory) {
    return abi.decode(vm.parseJsonType(json, path, schema_Borrow), (EIP712Types.Borrow));
  }

  function deserializeBorrowArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Borrow[] memory) {
    return abi.decode(vm.parseJsonTypeArray(json, path, schema_Borrow), (EIP712Types.Borrow[]));
  }

  function serialize(EIP712Types.Repay memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_Repay, abi.encode(value));
  }

  function serialize(
    EIP712Types.Repay memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_Repay, abi.encode(value));
  }

  function deserializeRepay(string memory json) public pure returns (EIP712Types.Repay memory) {
    return abi.decode(vm.parseJsonType(json, schema_Repay), (EIP712Types.Repay));
  }

  function deserializeRepay(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Repay memory) {
    return abi.decode(vm.parseJsonType(json, path, schema_Repay), (EIP712Types.Repay));
  }

  function deserializeRepayArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Repay[] memory) {
    return abi.decode(vm.parseJsonTypeArray(json, path, schema_Repay), (EIP712Types.Repay[]));
  }
}
