name: PR Comment

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Tests-PR]
    types:
      - completed

jobs:
  comment:
    uses: bgd-labs/github-workflows/.github/workflows/comment.yml@main
    secrets:
      READ_ONLY_PAT: ${{ secrets.READ_ONLY_PAT }}
